### ISSUE TITLE
GeoExample.PostgresTypes not available

### ISSUE THREAD

**Issue by stefanocdn** [bryanjos/geo_example#1]
Hi Bryan,

I am getting this error when I run **mix ecto.create**

> (UndefinedFunctionError) function GeoExample.PostgresTypes.find/2 is undefined (module GeoExample.PostgresTypes is not available)
>         GeoExample.PostgresTypes.find(%Postgrex.TypeInfo{array_elem: 0, base_type: 0, comp_elems: [], input: "boolin", oid: 16, output: "boolout", receive: "boolrecv", send: "boolsend", type: "bool"}, :any)
>         (postgrex) lib/postgrex/types.ex:111: Postgrex.Types.find/4
>         (postgrex) lib/postgrex/types.ex:104: anonymous fn/4 in Postgrex.Types.associate_type_infos/2
>         (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
>         (postgrex) lib/postgrex/types.ex:103: Postgrex.Types.associate_type_infos/2
>         (postgrex) lib/postgrex/type_server.ex:122: Postgrex.TypeServer.associate/2
>         (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
>         (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
> 

All my dependencies seem up to date. Any idea where that could come from?

**UPDATE**

Every time I run:

`mix deps.compile`

before any action, I don't get the above error. So I need to run mix deps.compile every time.
Could there be a dependency that does not compile correctly?

**Comment by RobinClowers** [comment]
@stefanocdn I ran into this issue, and I think it's actually a subtle bug in elixir / mix prior to 1.3.3. I was on 1.3.2 and upgrading fixed it.
